# fly.toml app configuration file generated for r0hin-cinema on 2024-08-27T00:02:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'r0hin-cinema'
primary_region = 'ord'

[http_service]
  internal_port = 11470
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']
  [http_service.http_options]
  idle_timeout = 300

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
